apiVersion: apps/v1
kind: Deployment
metadata:
  name: apsaso
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apsaso
  template:
    metadata:
      labels:
        app: apsaso
    spec:
      containers:
        - name: apsaso
          image: apsaso
          ports:
            - containerPort: 8080
