# Use a imagem base do MySQL
FROM mysql:5.7

# Defina variáveis de ambiente para configurar o MySQL (substitua com suas configurações)
ENV MYSQL_ROOT_PASSWORD=database
ENV MYSQL_DATABASE=systemdev
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=database
# Exponha a porta padrão do MySQL (3306)
EXPOSE 3306
